Algoritmo "Variáveis"
// Disciplina   : [Algorítimo e Lógica I]
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Igor Gurgel
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 
   nota: inteiro, nota2: real, nota: caracter, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Resultado:", nota)

Fimalgoritmo